Repository NikolaOgnjenovic/GeniusClone, pull requests merged in 2024-07, with the labels that each got.

#18 Fix/replace UUID attributes with class
  .idea/gradle.xml
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/ads/AdCreateRequest.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/ads/AdCreateResponse.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/ads/AdGetByIdResponse.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/reviews/ReviewCreateRequest.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/reviews/ReviewCreateResponse.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/reviews/ReviewGetByIdResponse.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Ad.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Review.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/ads/AdService.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/reviews/ReviewService.java
  backend/genius-clone/src/main/resources/application.properties
  docker-compose.yml
Labels: bug, enhancement

#19 Featutre/album crud
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  backend/genius-clone/src/main/java/com/mmul/geniusclone/controllers/albums/AlbumController.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/albums/post/PostAlbumRequest.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/dtos/albums/put/PutAlbumUpdateRequest.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Album.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Artist.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Band.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Genre.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Performer.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/repositories/albums/AlbumRepository.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/repositories/performers/PerformerRepository.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/albums/AlbumService.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/interfaces/IAlbumService.java
Labels: enhancement

#31 imporved songs table
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Playlist.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Song.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/songs/SongService.java
  frontend/src/app/components/pages/playlists-page/ui/playlist-page/playlist-page.component.ts
  frontend/src/app/components/pages/songs-page/songs-page.component.ts
  frontend/src/app/components/pages/songs-page/ui/songs-table/songs-table.component.html
  frontend/src/app/components/pages/songs-page/ui/update-song-modal/update-song-modal.component.ts
Labels: enhancement

#32 Fix all playlist bugs
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Performer.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Playlist.java
  backend/genius-clone/src/main/resources/application.properties
  docker-compose.yml
  frontend/src/app/components/pages/albums-page/ui/create-album-modal/create-album-modal.component.ts
  frontend/src/app/components/pages/playlists-page/playlists-page.component.ts
  frontend/src/app/components/pages/playlists-page/ui/create-playlist-page/create-playlist-page.component.ts
  frontend/src/app/components/pages/playlists-page/ui/update-playlist-page/update-playlist-page.component.ts
Labels: bug, enhancement

#33 Feature/add song image in playlist
  docker-compose.yml
  frontend/src/app/components/pages/playlists-page/ui/create-playlist-page/create-playlist-page.component.html
  frontend/src/app/components/pages/playlists-page/ui/update-playlist-page/update-playlist-page.component.html
Labels: bug, enhancement

#34 Add docs
  docs/GeniusClone.mdzip
  docs/GeniusClone.mdzip.bak
  docs/SpecifikacijaSIMS.docx
  docs/dml.sql
  docs/drop.sql
Labels: documentation, enhancement

#39 Hotfix merge
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Band.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Playlist.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Review.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/models/Song.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/albums/AlbumService.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/artist/ArtistService.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/bands/BandService.java
  backend/genius-clone/src/main/java/com/mmul/geniusclone/services/songs/SongService.java
Labels: bug, enhancement
